---
author:
  name: Садыков Ильдар Ильфатович
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

title: "Реферат на тему: "
subtitle: "Обзор расширений имен файлов."
license: "CC BY"
---

# Введение
В эпоху цифровых технологий каждый пользователь компьютера сталкивается с десятками различных файлов: документы, фотографии видео, программы. И для того чтобы операционная система и сам пользователь могли быстро понять, что это за файл и что в нем хранится, была придумана система расширений имен файлов.

**Расширение файла** - это последовательность символов, дописываемая после имени файла, которая индетифицирует его формат. Расширение отделено точкой в конце (пример: *paint.png,text.docx*).

# Цель работы
Объяснить классификацию основных типов расширений файлов и их назаначение.

# Основная часть
## Что такое расширение файла и почему оно важно?
Операционная система использует расширение, чтобы сопоставить файл с приложением, работующим с ним. Например, если файл имеет вид **text.txt** система понимает, что его стоит открывать в текстовом редакторе.

**Функции расширений: **

1) Индетификация типа данных.
2) Ассоциация с приоложениеями для операционной системы.
3) Безопасность. Способность различать потенциально опасные исполняяемые файлы.

## Классификация файлов:
Большинство расширений можно разделить на несколько небольших категорий по их неазаначению.

### **Текстовые файлы**
**Текстовые файлы** - файлы содержащие текстовую информацию в виде набора символов или с использованием форматируемой разметки.

- .txt - обычный текст.
- .doc/.docx - текстовые документы, используемые в word.
- .pdf - формат, удобный для печати и чтения, исполбзуемый для представления информации в электронном виде.
- .md/.qmd - расишрение, использующее размету markdown.

### **Таблицы и прзентации**
Такие файлы, которые позволюят представлять информацию в виде таблиц или слайдов в презентации.

- .xls/ .xlsx - таблицы Excel.
- .ppt/ .pptx - формат для презентаций.
- .csv - текстовый формат, представленный в виде таблицы.

### **Фото и изображения**
Формат представления графической информации.

- .jpg / .jpeg
- .png
- .gif - анимриованное изображение.
- .svg - формат представленный в векторном виде.

### **Видео и аудио**
Файлы мультимедиа.

- .mp3 - обычный формат аудио.
- .mp4 - обычный формат видео.
- .mov - формат Apple.
- .avi - популярный формат для видео.

### **Архивы**
Файлы-контейнеры, содержащие сжатые файлы.

- .zip
- .rar
- .7z

### **Исполняемые файлы**
Файлы, содержащие код, выполняющий определенный алгоритм.

- .exe
- .bat
- .apk -формат для android

### **Веб-файлы**
Формат, используемый для загрузки веб-страниц.

- .html/ .htm - базовый язык разметки веб-страниц.
- .css - формат стилей.
- .js - программа JavaScript
- .php - алгоритм для сервера.

### **Системные файлы**
Служебные файлы, используемые системой, не затрагиваемые обычным пользователем.

- .dll - библиотека используемых файлов windows.
- .ini - файлы конфигурации программы.
- .log - файлы логов (журнала событий)

## Проблема совместимости новых файлов.
Иногда пользователь сталкивается с файлом, расширения которого ему незнакомо. Что же тогда делать?

Зачастую система сама предлагает нужные приложения для открытия файла. Если же таких приложений нет, стоит поискать в интренете, что представляет из себя данный формат файла. 

Такие действия защитят от возможных скртых вирусов в подозрительных файлах, а так же даст понятие для чего используется новое расширение незнкамого файла.

# Вывод
Расширение файла - это простой, но критически важный элемент цифровой грамотности. Понимание того, какие файлы существую и для чего они предназначены, помогает эффективнее работать за компьютером, выбирать программы, а также дает возомжность избежать вредоностных программ.

В современном миру огромное множество различных расширений, но все же для пользователя достаточно несолько прорграмм из основых категорий: фото, тексты, видео, арихивы, программы, чтобы свободно пользововаться в цифровом пространстве.








