---
author:
  name: Садыков Ильдар Ильфатович
  group: НКАбд-05-24
  student-id: 1032205648
title: "Индивидуальный проект. Этап 3"
subtitle: "Архитектура компьютеров и операционные системы. Раздел «Операционные системы»"
---
# Цель работы

Добавить к сайту достижения: информацию о навыках, опыте, а также опубликовать два поста.

# Задание

1. Добавить информацию о навыках (Skills).
2. Добавить информацию об опыте (Experience).
3. Сделать пост по прошедшей неделе.
4. Добавить пост на тему "Язык разметки Markdown".

# Выполнение этапа проекта

## 1. Добавление информации о навыках

В соответствующий раздел сайта добавлена информация о профессиональных навыках.

## 2. Добавление информации об опыте

В раздел Experience добавлена информация о профессиональном опыте.

## 3. Создание поста по прошедшей неделе

Создан пост, описывающий события прошедшей недели.

## 4. Создание поста на тему "Язык разметки Markdown"

Создан пост, в котором рассказано об основах языка разметки Markdown, его синтаксисе и возможностях.

# Выводы

В ходе выполнения третьего этапа индивидуального проекта на сайт добавлена информация о навыках и опыте, а также два тематических поста.
