---
author:
  name: Садыков Ильдар Ильфатович
  group: НКАбд-05-24
  student-id: 1032205648
title: "Индивидуальный проект. Этап 2"
subtitle: "Архитектура компьютеров и операционные системы. Раздел «Операционные системы»"
---
# Цель работы

Добавить к сайту персональные данные: фотографию, биографию, информацию об интересах и образовании, а также опубликовать два поста.

# Задание

1. Разместить фотографию владельца сайта.
2. Разместить краткое описание владельца сайта (Biography).
3. Добавить информацию об интересах (Interests).
4. Добавить информацию об образовании (Education).
5. Сделать пост по прошедшей неделе.
6. Добавить пост на тему "Управление версиями. Git" или "Непрерывная интеграция и непрерывное развертывание (CI/CD)".

# Выполнение этапа проекта

## 1. Размещение фотографии владельца сайта

Фотография владельца сайта добавлена в соответствующий каталог и настроена в конфигурационных файлах сайта.

## 2. Добавление информации о владельце сайта

В раздел Biography добавлено краткое описание владельца сайта.

## 3. Добавление информации об интересах

В соответствующий раздел добавлена информация об интересах.

## 4. Добавление информации об образовании

В раздел Education добавлена информация об образовании.

## 5. Создание поста по прошедшей неделе

Создан пост, описывающий события прошедшей недели.

## 6. Создание поста на выбранную тему

Создан пост на тему "Управление версиями. Git", в котором рассказано об основах систем контроля версий и работе с Git.

# Выводы

В ходе выполнения второго этапа индивидуального проекта на сайт добавлена персональная информация и два тематических поста.
